<?php
/**
 * Burrow
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    Burrow
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class CurrencyData {

	public $table = 'currencies';

	public $records = array(
		array(
			'id' => '2',
			'created' => '2010-08-07 00:00:00',
			'modified' => '2011-09-04 22:49:35',
			'name' => 'Euros',
			'code' => 'EUR',
			'symbol' => '€',
			'is_enabled' => '1',
			'prefix' => '€',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'EUR',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '1'
		),
		array(
			'id' => '1',
			'created' => '2010-08-07 00:00:00',
			'modified' => '2011-05-04 07:49:32',
			'name' => 'U.S. Dollars',
			'code' => 'USD',
			'symbol' => '$',
			'is_enabled' => '1',
			'prefix' => '$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'USD',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '4',
			'created' => '2010-08-07 00:50:27',
			'modified' => '2011-09-03 19:04:19',
			'name' => 'Australian Dollars',
			'code' => 'AUD',
			'symbol' => '$',
			'is_enabled' => '1',
			'prefix' => '$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'AUD',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '1'
		),
		array(
			'id' => '5',
			'created' => '2010-08-07 00:50:51',
			'modified' => '2010-09-14 02:28:12',
			'name' => 'British Pounds',
			'code' => 'GBP',
			'symbol' => '£',
			'is_enabled' => '1',
			'prefix' => '£',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'GBP',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => ''
		),
		array(
			'id' => '6',
			'created' => '2010-08-07 00:51:11',
			'modified' => '2011-09-03 19:05:30',
			'name' => 'Canadian Dollars',
			'code' => 'CAD',
			'symbol' => '$',
			'is_enabled' => '1',
			'prefix' => '$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'CAD',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '8',
			'created' => '2010-08-07 00:51:47',
			'modified' => '2011-09-03 19:12:06',
			'name' => 'Danish Kroner',
			'code' => 'DKK',
			'symbol' => 'kr',
			'is_enabled' => '1',
			'prefix' => 'kr',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'DKK',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '9',
			'created' => '2010-08-07 00:52:05',
			'modified' => '2011-09-03 19:12:31',
			'name' => 'Hong Kong Dollars',
			'code' => 'HKD',
			'symbol' => 'HK$',
			'is_enabled' => '1',
			'prefix' => 'HK$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'HKD',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '28',
			'created' => '2011-10-10 14:03:27',
			'modified' => '2011-10-10 14:03:27',
			'name' => 'calle',
			'code' => '12',
			'symbol' => '&',
			'is_enabled' => '0',
			'prefix' => '',
			'is_prefix_display_on_left' => '1',
			'suffix' => '',
			'decimals' => '0',
			'dec_point' => '.0',
			'thousands_sep' => '.0',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '1'
		),
		array(
			'id' => '11',
			'created' => '2010-08-07 00:52:41',
			'modified' => '2011-09-03 19:13:03',
			'name' => 'Israeli New Shekels',
			'code' => 'ILS',
			'symbol' => '₪',
			'is_enabled' => '1',
			'prefix' => '₪',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'ILS',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '12',
			'created' => '2010-08-07 00:53:01',
			'modified' => '2011-09-03 19:13:19',
			'name' => 'Japanese Yen',
			'code' => 'JPY',
			'symbol' => '¥',
			'is_enabled' => '1',
			'prefix' => '¥',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'JPY',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '13',
			'created' => '2010-08-07 00:53:16',
			'modified' => '2011-09-03 19:13:39',
			'name' => 'Mexican Pesos',
			'code' => 'MXN',
			'symbol' => '$',
			'is_enabled' => '1',
			'prefix' => '$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'MXN',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '14',
			'created' => '2010-08-07 00:53:37',
			'modified' => '2011-09-03 19:14:01',
			'name' => 'New Zealand Dollars',
			'code' => 'NZD',
			'symbol' => '$',
			'is_enabled' => '1',
			'prefix' => '$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'NZD',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '15',
			'created' => '2010-08-07 00:53:53',
			'modified' => '2011-09-03 19:14:18',
			'name' => 'Norwegian Kroner',
			'code' => 'NOK',
			'symbol' => 'kr',
			'is_enabled' => '1',
			'prefix' => 'kr',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'NOK',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '16',
			'created' => '2010-08-07 00:54:12',
			'modified' => '2011-09-03 19:14:37',
			'name' => 'Philippine Pesos',
			'code' => 'PHP',
			'symbol' => 'Php',
			'is_enabled' => '1',
			'prefix' => 'Php',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'PHP',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '17',
			'created' => '2010-08-07 00:54:30',
			'modified' => '2011-09-03 19:14:58',
			'name' => 'Polish Zlotych',
			'code' => 'PLN',
			'symbol' => 'zł',
			'is_enabled' => '1',
			'prefix' => 'zł',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'PLN',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '18',
			'created' => '2010-08-07 00:54:49',
			'modified' => '2010-09-14 02:23:36',
			'name' => 'Singapore Dollars',
			'code' => 'SGD',
			'symbol' => '$',
			'is_enabled' => '1',
			'prefix' => '$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'SGD',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => ''
		),
		array(
			'id' => '19',
			'created' => '2010-08-07 00:55:04',
			'modified' => '2010-09-14 02:22:37',
			'name' => 'Swedish Kronor',
			'code' => 'SEK',
			'symbol' => 'kr',
			'is_enabled' => '1',
			'prefix' => 'kr',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'SEK',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => ''
		),
		array(
			'id' => '20',
			'created' => '2010-08-07 00:55:25',
			'modified' => '2010-09-14 02:22:16',
			'name' => 'Swiss Francs',
			'code' => 'CHF',
			'symbol' => 'CHF',
			'is_enabled' => '1',
			'prefix' => 'CHF',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'CHF',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => ''
		),
		array(
			'id' => '22',
			'created' => '2010-08-07 00:55:54',
			'modified' => '2011-05-04 06:16:11',
			'name' => 'Thai Baht',
			'code' => 'THB',
			'symbol' => '฿',
			'is_enabled' => '1',
			'prefix' => '฿',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'THB',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '23',
			'created' => '2010-08-07 00:55:54',
			'modified' => '2011-05-11 08:08:09',
			'name' => 'Indian Rupee',
			'code' => 'INR',
			'symbol' => 'र',
			'is_enabled' => '1',
			'prefix' => 'र',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'INR',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '26',
			'created' => '2011-09-13 10:59:30',
			'modified' => '2011-09-13 10:59:30',
			'name' => 'South African Rand',
			'code' => 'ZAR',
			'symbol' => 'ZAR',
			'is_enabled' => '1',
			'prefix' => '',
			'is_prefix_display_on_left' => '1',
			'suffix' => '',
			'decimals' => '',
			'dec_point' => '',
			'thousands_sep' => '',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '27',
			'created' => '2011-09-26 07:25:13',
			'modified' => '2011-09-26 07:25:13',
			'name' => ' BRL-CAD',
			'code' => 'BRL',
			'symbol' => 'R$',
			'is_enabled' => '1',
			'prefix' => '',
			'is_prefix_display_on_left' => '1',
			'suffix' => '',
			'decimals' => '',
			'dec_point' => '',
			'thousands_sep' => '',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '1'
		),
		array(
			'id' => '29',
			'created' => '2011-11-17 23:07:18',
			'modified' => '2011-11-17 23:07:18',
			'name' => 'Türk Lirası',
			'code' => 'TRY',
			'symbol' => 'TL',
			'is_enabled' => '1',
			'prefix' => '',
			'is_prefix_display_on_left' => '1',
			'suffix' => '',
			'decimals' => '',
			'dec_point' => '',
			'thousands_sep' => '',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '0'
		),
		array(
			'id' => '30',
			'created' => '2011-11-18 07:46:15',
			'modified' => '2011-11-18 07:46:15',
			'name' => 'INR',
			'code' => 'INR',
			'symbol' => 'IR',
			'is_enabled' => '1',
			'prefix' => '',
			'is_prefix_display_on_left' => '1',
			'suffix' => '',
			'decimals' => '',
			'dec_point' => '',
			'thousands_sep' => '',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '1'
		),
		array(
			'id' => '31',
			'created' => '2011-12-13 15:39:32',
			'modified' => '2011-12-13 15:39:32',
			'name' => 'Chilean Peso',
			'code' => 'CLP',
			'symbol' => '$',
			'is_enabled' => '1',
			'prefix' => '$',
			'is_prefix_display_on_left' => '1',
			'suffix' => 'CLP',
			'decimals' => '1',
			'dec_point' => ',',
			'thousands_sep' => '.',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => '1'
		),
		array(
			'id' => '32',
			'created' => '2012-02-06 03:58:42',
			'modified' => '2012-02-06 04:00:01',
			'name' => 'Romanian Leu',
			'code' => 'RON',
			'symbol' => 'Leu',
			'is_enabled' => '1',
			'prefix' => '',
			'is_prefix_display_on_left' => '1',
			'suffix' => '',
			'decimals' => '',
			'dec_point' => '',
			'thousands_sep' => '',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => ''
		),
		array(
			'id' => '53',
			'created' => '2012-06-13 21:21:20',
			'modified' => '2012-06-13 21:21:20',
			'name' => 'Egyptian Pound',
			'code' => 'EGP',
			'symbol' => 'EGP',
			'is_enabled' => '1',
			'prefix' => '',
			'is_prefix_display_on_left' => '1',
			'suffix' => '',
			'decimals' => '2',
			'dec_point' => '.',
			'thousands_sep' => ',',
			'locale' => '',
			'format_string' => '',
			'grouping_algorithm_callback' => '',
			'is_use_graphic_symbol' => ''
		),
	);

}
