<?php
/**
 * Burrow
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    Burrow
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class SettingData {

	public $table = 'settings';

	public $records = array(
		array(
			'id' => '1',
			'setting_category_id' => '21',
			'setting_category_parent_id' => '1',
			'name' => 'site.name',
			'value' => 'Burrow',
			'description' => 'This name will be used in all pages, emails.',
			'type' => 'text',
			'options' => '',
			'label' => 'Name',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '2',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'site.version',
			'value' => 'v2.0b5',
			'description' => 'This is the current version of the site, which will be displayed in the footer.',
			'type' => 'text',
			'options' => '',
			'label' => 'Version',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '3',
			'setting_category_id' => '24',
			'setting_category_parent_id' => '3',
			'name' => 'meta.keywords',
			'value' => 'agriya, dev1',
			'description' => 'These are the keywords used for improving search engine results of our site. (Comma separated for multiple keywords.)',
			'type' => 'text',
			'options' => '',
			'label' => 'Keywords',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '4',
			'setting_category_id' => '24',
			'setting_category_parent_id' => '3',
			'name' => 'meta.description',
			'value' => 'dev1 framework',
			'description' => 'This is the short description of your site, used by search engines on search result pages to display preview snippets for a given page.',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Description',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '5',
			'setting_category_id' => '22',
			'setting_category_parent_id' => '1',
			'name' => 'site.contact_email',
			'value' => '',
			'description' => 'This is the email address to which you will receive the mail from contact form.',
			'type' => 'text',
			'options' => '',
			'label' => 'Contact Email Address',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '9',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'user.using_to_login',
			'value' => 'username',
			'description' => 'Users will be able to login with chosen login handle (username or email address) along with their password.',
			'type' => 'select',
			'options' => 'username,
email',
			'label' => 'Login Handle',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '10',
			'setting_category_id' => '25',
			'setting_category_parent_id' => '3',
			'name' => 'site.tracking_script',
			'value' => '<script type=\"text/javascript\"> var _gaq = _gaq || []; _gaq.push([\'_setAccount\', \'UA-4819298-1\']); _gaq.push([\'_setDomainName\', \'burrow.dev.agriya.com\']); _gaq.push([\'_trackPageview\']); (function() { var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true; ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\'; var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s); })(); </script>',
			'description' => 'This is the site tracker script, used for track and analyze data about how people are getting to your website. e.g., Google Analytics. <a target=\"_blank\" href=\"http://www.google.com/analytics/\">http://www.google.com/analytics/</a>',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Site Tracker Code',
			'order' => '13',
			'plugin_name' => ''
		),
		array(
			'id' => '326',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.set_default_calendar_type',
			'value' => 'calendar',
			'description' => 'Admin can able to set the type of calendar either drop down box or calendar in property and request search.',
			'type' => 'select',
			'options' => 'dropdown, calendar',
			'label' => 'Calendar type in search',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '265',
			'setting_category_id' => '38',
			'setting_category_parent_id' => '8',
			'name' => 'property.listing_fee_payer',
			'value' => 'Site',
			'description' => '',
			'type' => 'radio',
			'options' => 'Host, Site',
			'label' => 'Who will pay gateway fee for property listing?',
			'order' => '26',
			'plugin_name' => 'Sudopay'
		),
		array(
			'id' => '264',
			'setting_category_id' => '38',
			'setting_category_parent_id' => '8',
			'name' => 'property.verify_fee_payer',
			'value' => 'Site',
			'description' => '',
			'type' => 'radio',
			'options' => 'Host, Site',
			'label' => 'Who will pay gateway fee for property verification?',
			'order' => '28',
			'plugin_name' => 'Sudopay'
		),
		array(
			'id' => '25',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.micro_thumb.width',
			'value' => '18',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Micro
thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '26',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.micro_thumb.height',
			'value' => '18',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '27',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.small_thumb.width',
			'value' => '28',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Small
thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '28',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.small_thumb.height',
			'value' => '28',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '29',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.medium_thumb.width',
			'value' => '45',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Medium thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '30',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.medium_thumb.height',
			'value' => '45',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '31',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.normal_thumb.width',
			'value' => '35',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Normal thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '32',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.normal_thumb.height',
			'value' => '35',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '33',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.big_thumb.width',
			'value' => '139',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Big
thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '34',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.big_thumb.height',
			'value' => '130',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '35',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.small_big_thumb.width',
			'value' => '170',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Small big thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '36',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.small_big_thumb.height',
			'value' => '170',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '37',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.medium_big_thumb.width',
			'value' => '458',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Medium big thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '38',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.medium_big_thumb.height',
			'value' => '303',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '39',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.very_big_thumb.width',
			'value' => '957',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Very big thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '40',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.very_big_thumb.height',
			'value' => '361',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '41',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_admin_activate_after_register',
			'value' => '0',
			'description' => 'On enabling this feature, admin need to approve each user after registration (User cannot login until admin approves)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Administrator Approval After Registration',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '42',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_email_verification_for_register',
			'value' => '1',
			'description' => 'On enabling this feature, user need to verify their email address provided during registration. (User cannot login until email address is verified)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Email Verification After Registration',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '43',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_auto_login_after_register',
			'value' => '0',
			'description' => 'On enabling this feature, users will be automatically logged-in after registration. (Only when \"Email Verification\" & \"Admin Approval\" is disabled)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Login After Registration',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '44',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_admin_mail_after_register',
			'value' => '1',
			'description' => 'On enabling this feature, notification mail will be sent to administrator on each registration.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Notify Administrator on Each Registration',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '45',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_welcome_mail_after_register',
			'value' => '1',
			'description' => 'On enabling this feature, users will receive a welcome mail after registration.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Sending Welcome Mail After Registration',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '47',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_logout_after_change_password',
			'value' => '1',
			'description' => 'On enabling this feature, users will be asked to log-in again.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto-Logout After Password Change',
			'order' => '8',
			'plugin_name' => ''
		),
		array(
			'id' => '56',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.date.format',
			'value' => '%b %d, %Y',
			'description' => 'This is the date format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date Format',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '57',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.datetime.format',
			'value' => '%b %d, %Y %I:%M %p',
			'description' => 'This is the date-time format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date-Time Format',
			'order' => '10',
			'plugin_name' => ''
		),
		array(
			'id' => '58',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.time.format',
			'value' => '%I:%M %p',
			'description' => 'This is the time format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Time Format',
			'order' => '8',
			'plugin_name' => ''
		),
		array(
			'id' => '59',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.date.tooltip',
			'value' => '%b %d, %Y %I:%M %p',
			'description' => 'This is the date tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date Tooltip Format',
			'order' => '7',
			'plugin_name' => ''
		),
		array(
			'id' => '60',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.time.tooltip',
			'value' => '%B %d, %Y (%A) %Z',
			'description' => 'This is the time tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Time Tooltip Format',
			'order' => '9',
			'plugin_name' => ''
		),
		array(
			'id' => '61',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.datetime.tooltip',
			'value' => '%B %d, %Y %I:%M:%S %p (%A) %Z',
			'description' => 'This is the date-time tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date-Time Tooltip Format',
			'order' => '11',
			'plugin_name' => ''
		),
		array(
			'id' => '71',
			'setting_category_id' => '23',
			'setting_category_parent_id' => '2',
			'name' => 'site.maintenance_mode',
			'value' => '0',
			'description' => 'On enabling this feature, only administrator can access the site (e.g., http://yourdomain.com/admin). Users will see a temporary page until you return to turn this off. (Turn this on, whenever you need to perform maintenance in the site.)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Maintenance Mode',
			'order' => '15',
			'plugin_name' => ''
		),
		array(
			'id' => '72',
			'setting_category_id' => '26',
			'setting_category_parent_id' => '4',
			'name' => 'site.language',
			'value' => 'en',
			'description' => 'The selected language will be used as default language all over the site (also for emails)',
			'type' => 'select',
			'options' => '',
			'label' => 'Site Language',
			'order' => '3',
			'plugin_name' => 'Translation'
		),
		array(
			'id' => '73',
			'setting_category_id' => '25',
			'setting_category_parent_id' => '3',
			'name' => 'site.robots',
			'value' => '',
			'description' => 'Content for robots.txt; (search engine) robots specific instructions. Refer,<a target=\"_blank\" href=\"http://www.robotstxt.org/\">http://www.robotstxt.org/</a> for syntax and usage.',
			'type' => 'textarea',
			'options' => '',
			'label' => 'robots.txt',
			'order' => '14',
			'plugin_name' => ''
		),
		array(
			'id' => '92',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_allow_user_to_switch_language',
			'value' => '1',
			'description' => 'On enabling this feature, users can change site language to their choice.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable User to Switch Language',
			'order' => '14',
			'plugin_name' => ''
		),
		array(
			'id' => '229',
			'setting_category_id' => '42',
			'setting_category_parent_id' => '11',
			'name' => 'messages.send_notification_mail_for_sender',
			'value' => '0',
			'description' => 'On enabling this feature, sender will receive same email sent by him for his future reference.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Notify Mail to Sender',
			'order' => '3',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '168',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '6',
			'name' => 'wallet.max_wallet_amount',
			'value' => '200000',
			'description' => 'This is the maximum amount a user can add to his wallet. (If left empty, then, no maximum amount restrictions)',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Wallet Funding Limit',
			'order' => '10',
			'plugin_name' => 'Wallet'
		),
		array(
			'id' => '167',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '6',
			'name' => 'wallet.min_wallet_amount',
			'value' => '10',
			'description' => 'This is the minimum amount a user can add to his wallet.',
			'type' => 'text',
			'options' => '',
			'label' => 'Minimum Wallet Funding Limit',
			'order' => '11',
			'plugin_name' => 'Wallet'
		),
		array(
			'id' => '166',
			'setting_category_id' => '47',
			'setting_category_parent_id' => '14',
			'name' => 'affiliate.site_commission_type',
			'value' => 'amount',
			'description' => 'The selected option will be used as the default fee type during affiliate cash withdrawal.',
			'type' => 'select',
			'options' => 'percentage,amount',
			'label' => '',
			'order' => '8',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '165',
			'setting_category_id' => '47',
			'setting_category_parent_id' => '14',
			'name' => 'affiliate.site_commission_amount',
			'value' => '1',
			'description' => 'This is the amount which will be taken during affiliate cash withdrawal. (If left empty, then, no fee will be taken)',
			'type' => 'text',
			'options' => '',
			'label' => 'Transaction Fee',
			'order' => '7',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '164',
			'setting_category_id' => '45',
			'setting_category_parent_id' => '14',
			'name' => 'affiliate.referral_cookie_expire_time',
			'value' => '10',
			'description' => 'This is the maximum time after which the referral cookie will be expired or unusable.',
			'type' => 'text',
			'options' => '',
			'label' => 'Referral Cookie Expire Time',
			'order' => '2',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '163',
			'setting_category_id' => '46',
			'setting_category_parent_id' => '14',
			'name' => 'affiliate.commission_on_every_property_booking',
			'value' => '1',
			'description' => 'On enabling this feature, affiliate user will earn commission amount on every referral booked. (Turn this off, if you want affiliate user to be payed only for his first referral)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Pay Commission On Every Property Booked',
			'order' => '3',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '162',
			'setting_category_id' => '46',
			'setting_category_parent_id' => '14',
			'name' => 'affiliate.commission_holding_period',
			'value' => '0',
			'description' => 'This is the maximum number of days in which the commission amount is in holding state. During this state, amount cannot be requested for withdrawal.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Commission Holding Period',
			'order' => '4',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '161',
			'setting_category_id' => '47',
			'setting_category_parent_id' => '14',
			'name' => 'affiliate.payment_threshold_for_threshold_limit_reach',
			'value' => '1',
			'description' => 'This is the minimum amount to get reached for a affiliate user can make a withdraw request.',
			'type' => 'text',
			'options' => '',
			'label' => 'Minimum Withdrawal Threshold Limit',
			'order' => '6',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '228',
			'setting_category_id' => '42',
			'setting_category_parent_id' => '11',
			'name' => 'messages.is_send_email_on_new_message',
			'value' => '1',
			'description' => 'On enabling this feature, users will be notified by an email for every new message.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Notify via Mail on New Message',
			'order' => '2',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '227',
			'setting_category_id' => '42',
			'setting_category_parent_id' => '11',
			'name' => 'messages.is_send_internal_message',
			'value' => '1',
			'description' => 'On disabling this feature, user cannot able to send message to other user in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Send Message Option',
			'order' => '1',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '159',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.datetimehighlight.tooltip',
			'value' => '%B %d, %Y %I:%M:%S %p (%A) %Z',
			'description' => 'This is the date-time highlight tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date-Time Highlight Tooltip',
			'order' => '12',
			'plugin_name' => ''
		),
		array(
			'id' => '169',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'facebook.is_enabled_facebook_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their site account using Facebook.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Facebook',
			'order' => '12',
			'plugin_name' => ''
		),
		array(
			'id' => '171',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.secrect_key',
			'value' => '41565c9584f21c156ba11fbf78ab47fd',
			'description' => 'This is the Facebook secret key used for authentication and other Facebook related plugins support',
			'type' => 'text',
			'options' => '',
			'label' => 'Secret Key',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '172',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.consumer_key',
			'value' => '1EfhgSlKRTVRtN5g1Ncw',
			'description' => 'This is the consumer key used for authentication and posting on Twitter.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Key',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '173',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.consumer_secret',
			'value' => 'gMnF2YoiRj3UT0f2HY9gKf5Q2zCmOpYBRPvQZZiqao',
			'description' => 'This is the consumer secret key used for authentication and posting on Twitter.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Secret Key',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '174',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.site_username',
			'value' => 'burrowdev',
			'description' => 'This is the Twitter username of the account has been created.',
			'type' => 'text',
			'options' => '',
			'label' => 'Twitter Username',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '175',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.site_user_access_key',
			'value' => '4RhHRYARjruDW4XS5EjJohlwV48nSrgIefbpx5Ov8s',
			'description' => 'This will be automatically updated when on clicking \"Update Twitter Credentials\" link. (Required for posting in Twitter)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Key',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '176',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.site_user_access_token',
			'value' => '423054625-CEV6Ne7zCsafHTNjZzX4ktKk4wKPY0TpissyvsTI',
			'description' => 'This will be automatically updated when on clicking \"Update Twitter Credentials\" link. (Required for posting in Twitter)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Token',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '177',
			'setting_category_id' => '13',
			'setting_category_parent_id' => '0',
			'name' => 'twitter.prompt_for_email_after_register',
			'value' => '1',
			'description' => 'Prompts
twitter user to enter email after twitter registration.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Prompt for email after registration',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '178',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.fb_access_token',
			'value' => '152575094815970|29b71cceed4e35b10b201465.1-100002427863037|-1IK9E5E7XQxR_1gkXWZuQJitHY',
			'description' => 'This will be automatically updated when on clicking \"Update Facebook Credentials\" link. (Required for posting in Facebook)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Token',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '179',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.fb_user_id',
			'value' => '100002427863037',
			'description' => 'This will be automatically updated when on clicking \"Update Facebook Credentials\" link. (Required for posting in Facebook)',
			'type' => 'text',
			'options' => '',
			'label' => 'User ID',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '180',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.page_id',
			'value' => '219299451443212',
			'description' => 'This is the Facebook page ID, if specified, any new property added will be posted in this page wall, instead of the configured account.',
			'type' => 'text',
			'options' => '',
			'label' => 'Page ID',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '181',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.app_id',
			'value' => '152575094815970',
			'description' => 'This is the application ID used in login and post.',
			'type' => 'text',
			'options' => '',
			'label' => 'Application ID',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '182',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'twitter.is_enabled_twitter_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their site account using Twitter.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Twitter',
			'order' => '14',
			'plugin_name' => ''
		),
		array(
			'id' => '184',
			'setting_category_id' => '40',
			'setting_category_parent_id' => '10',
			'name' => 'suspicious_detector.suspiciouswords',
			'value' => 'stupid
fool
\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*([,;]\\s*\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*)*
^0[234679]{1}[\\s]{0,1}[\\-]{0,1}[\\s]{0,1}[1-9]{1}[0-9]{6}$',
			'description' => 'The suspicious words given will be matched with user given message and will be auto flagged if such words are found. (Note: Suspicious detection will be checked during property, request creation & send message. Detection words should be newline separated.)',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Suspicious Words',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '190',
			'setting_category_id' => '33',
			'setting_category_parent_id' => '7',
			'name' => 'property.days_after_amount_withdraw',
			'value' => '1',
			'description' => 'This is the maximum number of days after checkin in which the booking amount is in holding state. Traveler can raise dispute \"Doesn\'t match the specification as mentioned by the host\" within given days. If dispute raised, then amount will be blocked.',
			'type' => 'text',
			'options' => '',
			'label' => 'Days after amount will be cleared to host',
			'order' => '23',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '191',
			'setting_category_id' => '37',
			'setting_category_parent_id' => '8',
			'name' => 'property.booking_service_fee',
			'value' => '7',
			'description' => 'This is the traveler service fee percentage which will be calculate from booking amount when on booking the property.',
			'type' => 'text',
			'options' => '',
			'label' => 'Traveler Service Fee',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '192',
			'setting_category_id' => '33',
			'setting_category_parent_id' => '7',
			'name' => 'property.auto_expire',
			'value' => '1',
			'description' => 'This is the maximum number of days after in which unaccepted bookings are automatically expired and amount will be refunded to traveler.',
			'type' => 'text',
			'options' => '',
			'label' => 'Days after unaccepted booking auto expire',
			'order' => '20',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '196',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '7',
			'name' => 'property.maximum_title_length',
			'value' => '200',
			'description' => 'This is the maximum character allowed for property title.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Character for Property Title',
			'order' => '11',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '197',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '7',
			'name' => 'property.maximum_description_length',
			'value' => '450',
			'description' => 'This is the maximum character allowed for property description.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Character for Property Description',
			'order' => '13',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '198',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '7',
			'name' => 'property.minimum_title_length',
			'value' => '8',
			'description' => 'This is the minimum character allowed for property title',
			'type' => 'text',
			'options' => '',
			'label' => 'Minimum Character for Property Title',
			'order' => '12',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '244',
			'setting_category_id' => '41',
			'setting_category_parent_id' => '10',
			'name' => 'request.auto_suspend_request_on_system_flag',
			'value' => '1',
			'description' => 'Auto suspended requests will not display in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Suspend Request on System Flag',
			'order' => '26',
			'plugin_name' => ''
		),
		array(
			'id' => '312',
			'setting_category_id' => '56',
			'setting_category_parent_id' => '4',
			'name' => 'site.is_currency_conversion_history_updation',
			'value' => '1',
			'description' => 'On enabling this feature, latest currency conversion rate, old rate are stored in currency conversion History.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Currency Conversion History Updation',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '245',
			'setting_category_id' => '41',
			'setting_category_parent_id' => '10',
			'name' => 'property.auto_suspend_message_on_system_flag',
			'value' => '1',
			'description' => 'Auto suspended messages will not display in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Suspend Message on System Flag',
			'order' => '26',
			'plugin_name' => ''
		),
		array(
			'id' => '203',
			'setting_category_id' => '41',
			'setting_category_parent_id' => '10',
			'name' => 'property.auto_suspend_property_on_system_flag',
			'value' => '1',
			'description' => 'Auto suspended properties will not display in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Suspend Property on System Flag',
			'order' => '26',
			'plugin_name' => ''
		),
		array(
			'id' => '310',
			'setting_category_id' => '23',
			'setting_category_parent_id' => '2',
			'name' => 'site.is_ssl_enabled',
			'value' => '0',
			'description' => 'On enabling this feature, users login, registration and payment page will be carried through more secure way. (Requires purchase of an SSL certificate if this option is in disabled state)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable SSL (Secure Socket Layer)',
			'order' => '20',
			'plugin_name' => ''
		),
		array(
			'id' => '311',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '7',
			'name' => 'properties.max_upload_photo',
			'value' => '5',
			'description' => 'This is the maximum number of photos can upload by host per property.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Number of Photos Per Property',
			'order' => '0',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '206',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'property.payment_gateway_fee_id',
			'value' => 'Site',
			'description' => '',
			'type' => 'radio',
			'options' => 'Host, Site, Site and Host',
			'label' => 'Who will pay gateway fee for booking?',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '216',
			'setting_category_id' => '22',
			'setting_category_parent_id' => '1',
			'name' => 'site.reply_to_email',
			'value' => '',
			'description' => '\"Reply-To\" email header for all emails. Leave it empty to receive replies as usual (to \"From\" email address).',
			'type' => 'text',
			'options' => '',
			'label' => 'Reply Email
address',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '217',
			'setting_category_id' => '22',
			'setting_category_parent_id' => '1',
			'name' => 'site.from_email',
			'value' => 'productdemo.admin+from+burrow@gmail.com',
			'description' => 'This is the email address that will appear in the \"From\" field of all emails sent from the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'From Email address',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '220',
			'setting_category_id' => '53',
			'setting_category_parent_id' => '15',
			'name' => 'flickr.api_key',
			'value' => '70a50b14e9e203eab939e4ce223515b9',
			'description' => 'This is the configured Flickr API Key.',
			'type' => 'text',
			'options' => '',
			'label' => 'API Key',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '370',
			'setting_category_id' => '84',
			'setting_category_parent_id' => '82',
			'name' => 'widget.browse_script',
			'value' => '',
			'description' => 'This is the browse page script, used for display banners on Property browse page',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '223',
			'setting_category_id' => '35',
			'setting_category_parent_id' => '7',
			'name' => 'barcode.is_barcode_enabled',
			'value' => '1',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Barcode',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '224',
			'setting_category_id' => '35',
			'setting_category_parent_id' => '7',
			'name' => 'barcode.width',
			'value' => '120',
			'description' => 'This is the width of the barcode which is generated for ticket.',
			'type' => 'text',
			'options' => '',
			'label' => 'Barcode Width',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '225',
			'setting_category_id' => '35',
			'setting_category_parent_id' => '7',
			'name' => 'barcode.height',
			'value' => '120',
			'description' => 'This is the height of the barcode which is generated for coupons.',
			'type' => 'text',
			'options' => '',
			'label' => 'Barcode Height',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '226',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'site.distance_limit',
			'value' => '30',
			'description' => 'Maximum distance covered for property search from the entered location',
			'type' => 'text',
			'options' => '',
			'label' => 'Property Search Limit',
			'order' => '15',
			'plugin_name' => ''
		),
		array(
			'id' => '230',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.site_twitter_url',
			'value' => 'http://twitter.com/burrowdev',
			'description' => 'This is the site Twitter URL used displayed in the footer.',
			'type' => 'text',
			'options' => '',
			'label' => 'Twitter Account URL',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '231',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.site_facebook_url',
			'value' => 'http://www.facebook.com/pages/Burrowdemo/219299451443212?sk=wall',
			'description' => 'This is the site Facebook URL used displayed in the footer.',
			'type' => 'text',
			'options' => '',
			'label' => 'Facebook Account URL',
			'order' => '7',
			'plugin_name' => ''
		),
		array(
			'id' => '232',
			'setting_category_id' => '31',
			'setting_category_parent_id' => '6',
			'name' => 'user.minimum_withdraw_amount',
			'value' => '2',
			'description' => 'This is the minimum amount a user can withdraw from their wallet.',
			'type' => 'text',
			'options' => '',
			'label' => 'Minimum Wallet Withdrawal Amount',
			'order' => '2',
			'plugin_name' => 'Withdrawals'
		),
		array(
			'id' => '233',
			'setting_category_id' => '31',
			'setting_category_parent_id' => '6',
			'name' => 'user.maximum_withdraw_amount',
			'value' => '10000',
			'description' => 'This is the maximum amount a user can withdraw from their wallet.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Wallet Withdrawal Amount',
			'order' => '3',
			'plugin_name' => 'Withdrawals'
		),
		array(
			'id' => '371',
			'setting_category_id' => '85',
			'setting_category_parent_id' => '82',
			'name' => 'widget.property_script',
			'value' => '',
			'description' => 'This is the property view page script, used for display banners on property view page',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '235',
			'setting_category_id' => '44',
			'setting_category_parent_id' => '13',
			'name' => 'dispute.discussion_threshold_for_admin_decision',
			'value' => '8',
			'description' => 'Admin will take decision, after given number of conversation between traveler and host.',
			'type' => 'text',
			'options' => '',
			'label' => 'Discussion Threshold for Admin Decision',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '236',
			'setting_category_id' => '44',
			'setting_category_parent_id' => '13',
			'name' => 'dispute.days_left_for_disputed_user_to_reply',
			'value' => '5',
			'description' => 'Maximum number of days to reply for a dispute raised in booking',
			'type' => 'text',
			'options' => '',
			'label' => 'Number of days to reply a dispute',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '237',
			'setting_category_id' => '44',
			'setting_category_parent_id' => '13',
			'name' => 'dispute.refund_amount_during_dispute_cancellation',
			'value' => '50',
			'description' => 'Given percentage will be deduct from booking amount and refund to traveler when traveler raised dispute if \"Doesn\'t match the specification as mentioned by the host\" and admin decision favored to traveler.',
			'type' => 'text',
			'options' => '',
			'label' => 'Refund Percentage to Traveler for Property Specification Dispute',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '238',
			'setting_category_id' => '38',
			'setting_category_parent_id' => '8',
			'name' => 'property.listing_fee',
			'value' => '0',
			'description' => 'For free property listing, set it as \"0\".',
			'type' => 'text',
			'options' => '',
			'label' => 'Property Listing Fee',
			'order' => '25',
			'plugin_name' => ''
		),
		array(
			'id' => '313',
			'setting_category_id' => '58',
			'setting_category_parent_id' => '15',
			'name' => 'google.translation_api_key',
			'value' => '',
			'description' => 'This is the configured Google Translate API key.',
			'type' => 'text',
			'options' => '',
			'label' => 'API Key',
			'order' => '0',
			'plugin_name' => 'Translation'
		),
		array(
			'id' => '314',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.normal_big_thumb.width',
			'value' => '161',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Normal Big thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '315',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.normal_big_thumb.height',
			'value' => '119',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '241',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '7',
			'name' => 'property.is_auto_approve',
			'value' => '1',
			'description' => 'On disabling this feature, admin need to approve each property after added (Property will not list in site until admin approves)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Approval After Property Add',
			'order' => '25',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '242',
			'setting_category_id' => '38',
			'setting_category_parent_id' => '8',
			'name' => 'property.verify_fee',
			'value' => '0',
			'description' => 'For free property verification, set it as \"0\".',
			'type' => 'text',
			'options' => '',
			'label' => 'Property Verification Fee',
			'order' => '27',
			'plugin_name' => ''
		),
		array(
			'id' => '256',
			'setting_category_id' => '50',
			'setting_category_parent_id' => '15',
			'name' => 'invite.yahoo_consumer_key',
			'value' => 'dj0yJmk9MFlSemwzcFRNYXF6JmQ9WVdrOU1ISlBTRk5rTjJVbWNHbzlPREk0TXpZMk1UWXkmcz1jb25zdW1lcnNlY3JldCZ4PWQ2',
			'description' => 'This is configured Yahoo consumer key.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Key',
			'order' => '12',
			'plugin_name' => ''
		),
		array(
			'id' => '257',
			'setting_category_id' => '50',
			'setting_category_parent_id' => '15',
			'name' => 'invite.yahoo_secret_key',
			'value' => '309d66712b0e3d6d51c675a3b1ca03ca829a8b60',
			'description' => 'This is configured Yahoo consumer secret key.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Secret',
			'order' => '13',
			'plugin_name' => ''
		),
		array(
			'id' => '259',
			'setting_category_id' => '56',
			'setting_category_parent_id' => '4',
			'name' => 'site.currency_symbol_place',
			'value' => 'right',
			'description' => 'The selected position will be used as default currency symbol position all over the site (also for emails)',
			'type' => 'select',
			'options' => 'right, left',
			'label' => 'Currency Symbol Position',
			'order' => '10',
			'plugin_name' => ''
		),
		array(
			'id' => '260',
			'setting_category_id' => '37',
			'setting_category_parent_id' => '8',
			'name' => 'property.host_commission_amount',
			'value' => '',
			'description' => 'This is the host service fee percentage which will be calculate from booking amount.',
			'type' => 'text',
			'options' => '',
			'label' => 'Host Service Fee',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '261',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '7',
			'name' => 'property.minimum_nights',
			'value' => '5',
			'description' => 'This is the maximum value the user can select for \"Minimum nights\" in property add & edit page',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximim value for minimum nights',
			'order' => '12',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '262',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '7',
			'name' => 'property.maximum_nights',
			'value' => '30',
			'description' => 'This is the maximum value the user can select for \"Maximum nights\"',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximim value for maximum nights',
			'order' => '12',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '369',
			'setting_category_id' => '83',
			'setting_category_parent_id' => '82',
			'name' => 'widget.footer_script',
			'value' => '<img src=\"http://placehold.it/728X90\" alt =\"728X90\" width=\"728\" height=\"90\"/>',
			'description' => 'This is the footer page script, used for display banners on footer page',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '269',
			'setting_category_id' => '39',
			'setting_category_parent_id' => '9',
			'name' => 'request.is_auto_approve',
			'value' => '0',
			'description' => 'On enabling this feature, admin need to approve each request after added (Request will not list in site until admin approves)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Administrator Approval After Request Add',
			'order' => '12',
			'plugin_name' => 'Requests'
		),
		array(
			'id' => '271',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'site.exact_distance_limit',
			'value' => '2',
			'description' => 'This is the maximum distance limit to mark the property as \"Exact\" in property search.',
			'type' => 'text',
			'options' => '',
			'label' => 'Distance limit to mark as \"Exact\"',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '272',
			'setting_category_id' => '33',
			'setting_category_parent_id' => '7',
			'name' => 'site.maximum_negotiation_allowed_discount',
			'value' => '50',
			'description' => 'This is the maximum negotiation discount percentage can given by host to traveler for a booking.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Negotiation Discount',
			'order' => '17',
			'plugin_name' => ''
		),
		array(
			'id' => '295',
			'setting_category_id' => '21',
			'setting_category_parent_id' => '1',
			'name' => 'site.slogan_text',
			'value' => 'Book your burrow',
			'description' => 'This text will be used as to display in home page.',
			'type' => 'text',
			'options' => '',
			'label' => 'Slogan',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '363',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.rectagle_thumb.width',
			'value' => '155',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => 'Retagle thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '364',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.rectagle_thumb.height',
			'value' => '96',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => 'Retagle thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '283',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.collection_thumb.width',
			'value' => '310',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Collection thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '284',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.collection_thumb.height',
			'value' => '192',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '285',
			'setting_category_id' => '23',
			'setting_category_parent_id' => '2',
			'name' => 'site.look_up_url',
			'value' => 'http://whois.sc/',
			'description' => 'URL prefix for whois lookup service. Will be used in whois links found in ##USER_LOGIN## pages to resolve users\' IP to where they are from&mdash;often down to the city or neighborhood or country. This is a security feature.',
			'type' => 'text',
			'options' => '',
			'label' => 'Whois Lookup URL',
			'order' => '30',
			'plugin_name' => ''
		),
		array(
			'id' => '286',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '55',
			'name' => 'site.iphone_app_key',
			'value' => '12345678',
			'description' => 'This is the security key used for iPhone App',
			'type' => 'text',
			'options' => '',
			'label' => 'Application Key',
			'order' => '15',
			'plugin_name' => 'MobileApp'
		),
		array(
			'id' => '287',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.iphone_big_thumb.width',
			'value' => '160',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'iPhone Big Thumb',
			'order' => '13',
			'plugin_name' => ''
		),
		array(
			'id' => '288',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.iphone_big_thumb.height',
			'value' => '102',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '14',
			'plugin_name' => ''
		),
		array(
			'id' => '289',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.iphone_small_thumb.width',
			'value' => '100',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'iPhone Small Thumb',
			'order' => '15',
			'plugin_name' => ''
		),
		array(
			'id' => '290',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.iphone_small_thumb.height',
			'value' => '60',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '291',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.collage_thumb.width',
			'value' => '310',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Collage thumb',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '292',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '65',
			'name' => 'thumb_size.collage_thumb.height',
			'value' => '96',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '297',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.is_property_verification_enabled',
			'value' => '1',
			'description' => 'On enabling this feature, host can request admin to check his property and set it as verified property.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Property Verification',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '361',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_secure',
			'value' => 'Only the listed pages',
			'description' => '',
			'type' => 'select',
			'options' => 'Every page except the listed pages, Only the listed pages',
			'label' => 'Pages which require an explicit login',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '362',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_pages',
			'value' => 'projects/add',
			'description' => 'Enter pages comma separated',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Pages',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '300',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_allow_user_to_switch_currency',
			'value' => '1',
			'description' => 'On enabling this feature, users can change site currency to their choice.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable User to Switch Currency',
			'order' => '15',
			'plugin_name' => ''
		),
		array(
			'id' => '301',
			'setting_category_id' => '56',
			'setting_category_parent_id' => '4',
			'name' => 'site.currency_id',
			'value' => '1',
			'description' => 'The selected currency will be used in site to display as default currency in all pages. (Replaced with user selected currency)',
			'type' => 'select',
			'options' => '',
			'label' => 'Default Display Currency',
			'order' => '7',
			'plugin_name' => ''
		),
		array(
			'id' => '302',
			'setting_category_id' => '56',
			'setting_category_parent_id' => '4',
			'name' => 'site.is_auto_currency_updation',
			'value' => '1',
			'description' => 'On enabling this feature, latest currency conversion values are automatically updated <a target=\"_blank\" href=\"http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml\"> http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml</a> via cron everyday. (Disable this, if you have manually updated certain currency values in ##MASTER_CURRENCY##)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Automatic Currency Conversion Updation',
			'order' => '9',
			'plugin_name' => ''
		),
		array(
			'id' => '303',
			'setting_category_id' => '38',
			'setting_category_parent_id' => '8',
			'name' => 'user.signup_fee',
			'value' => '0',
			'description' => 'For free signup , set it as \"0\".',
			'type' => 'text',
			'options' => '',
			'label' => 'User Membership Fee',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '304',
			'setting_category_id' => '38',
			'setting_category_parent_id' => '8',
			'name' => 'user.signup_fee_payer',
			'value' => 'Site',
			'description' => '',
			'type' => 'radio',
			'options' => 'User, Site',
			'label' => 'Who will pay gateway fee for membership?',
			'order' => '17',
			'plugin_name' => 'Sudopay'
		),
		array(
			'id' => '305',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.is_enable_security_deposit',
			'value' => '0',
			'description' => 'On enabling this feature, host can set security deposit amount for his property. Traveler will pay booking amount with security deposit at the time of booking. It will automatically refund to traveler if no dispute was raised by host.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Security Deposit',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '306',
			'setting_category_id' => '33',
			'setting_category_parent_id' => '7',
			'name' => 'property.auto_refund_security_deposit',
			'value' => '0',
			'description' => 'This is the maximum number of days after checkout in which the security deposit amount is in holding state. Host can raise dispute \"Claim the security damage from traveler\" within given days. If dispute raised, then security deposit will be blocked.',
			'type' => '',
			'options' => '',
			'label' => 'Days after secuity deposit will be refunded to traveler',
			'order' => '0',
			'plugin_name' => 'Properties'
		),
		array(
			'id' => '307',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_enable_normal_registration',
			'value' => '1',
			'description' => 'On disabling this feature, user will be registered via Facebook, Twitter & OpenID.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Normal Registration & Login',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '360',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_cookie_prefix',
			'value' => 'sfp',
			'description' => 'A string used as prefix to build the persistent login cookie name. Characters allowed: ASCII letters ([A-Z], [a-z]), digits ([0-9]), hyphens (\"-\") or underscores (\"_\"). Previous cookies stored in user ',
			'type' => 'text',
			'options' => '',
			'label' => 'Cookie name prefix',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '309',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.is_enable_property_count',
			'value' => '1',
			'description' => 'This is to hide total available properties on the site. You may want to check this when your site is new and you have relatively less properties on the site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Hide properties count',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '359',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_maxlogins',
			'value' => '5',
			'description' => 'The maximum number of Persistent Logins remembered per user.',
			'type' => 'select',
			'options' => '5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100',
			'label' => 'Remembered logins per user',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '358',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_maxlife',
			'value' => '5',
			'description' => 'The maximum number of days for which a remember me session is valid; afterwards, the user will need to log in again.  Enter 0 for no expiration.',
			'type' => 'text',
			'options' => '',
			'label' => 'Days to remember the user',
			'order' => '10',
			'plugin_name' => ''
		),
		array(
			'id' => '319',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.days_calculation_mode',
			'value' => 'Night',
			'description' => 'If Day option is chosen, then 3 days will be counted when user chooses date 1, 2 & 3. If Night option is chosen, then 2 days will be counted when user chooses date 1, 2 & 3.',
			'type' => 'radio',
			'options' => 'Day,Night',
			'label' => 'Days Calculation Mode',
			'order' => '17',
			'plugin_name' => ''
		),
		array(
			'id' => '321',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.is_show_flickr',
			'value' => '0',
			'description' => 'On enable this feature, traveler can view flickr photos of property city on property view page.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable to show Flickr photos of the property city',
			'order' => '19',
			'plugin_name' => ''
		),
		array(
			'id' => '322',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.is_show_amenities_around',
			'value' => '0',
			'description' => 'On enable this feature, traveler can view amenities like restaurant, cafe etc. around the property city on property view page.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable to show Amenities around property city',
			'order' => '20',
			'plugin_name' => ''
		),
		array(
			'id' => '324',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.is_enable_edit_property_image',
			'value' => '1',
			'description' => 'On enabling this feature, host can delete and re upload the property image.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable delete option for property image in edit page',
			'order' => '17',
			'plugin_name' => ''
		),
		array(
			'id' => '327',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.count_display_type',
			'value' => 'rounded',
			'description' => 'Here you can set the type of count display whether it is rounded or real numbers?',
			'type' => 'select',
			'options' => 'rounded, real',
			'label' => 'Count display type',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '328',
			'setting_category_id' => '34',
			'setting_category_parent_id' => '7',
			'name' => 'property.weekstartson',
			'value' => 'Sunday',
			'description' => 'This is the start day of week which is displayed in our site calendar.',
			'type' => 'select',
			'options' => 'Sunday, Monday, Saturday',
			'label' => 'Week Starts on',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '329',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'Hook.bootstraps',
			'value' => 'SecurityQuestions,LaunchModes,MobileApp,Translation,Wallet,Withdrawals,Properties,PropertyFavorites,PropertyFlags',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '330',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'googleplus.is_enabled_googleplus_connect',
			'value' => '1',
			'description' => 'By enabling this feature, users can authenticate their Burrow account using Google+.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Google+',
			'order' => '17',
			'plugin_name' => ''
		),
		array(
			'id' => '331',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'google.is_enabled_google_connect',
			'value' => '1',
			'description' => 'By enabling this feature, users can authenticate their Burrow account using Google.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Google',
			'order' => '18',
			'plugin_name' => ''
		),
		array(
			'id' => '332',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'yahoo.is_enabled_yahoo_connect',
			'value' => '1',
			'description' => 'By enabling this feature, users can authenticate their Burrow account using Yahoo!.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Yahoo!',
			'order' => '19',
			'plugin_name' => ''
		),
		array(
			'id' => '333',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'linkedin.is_enabled_linkedin_connect',
			'value' => '1',
			'description' => 'By enabling this feature, users can authenticate their Burrow account using Linkedin.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Linkedin',
			'order' => '20',
			'plugin_name' => ''
		),
		array(
			'id' => '334',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'openid.is_enabled_openid_connect',
			'value' => '1',
			'description' => 'By enabling this feature, users can authenticate their Burrow account using OpenID.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable OpenID',
			'order' => '21',
			'plugin_name' => ''
		),
		array(
			'id' => '336',
			'setting_category_id' => '51',
			'setting_category_parent_id' => '15',
			'name' => 'google.consumer_key',
			'value' => '1061226080208.apps.googleusercontent.com',
			'description' => 'This is the Consumer ID used in Gmail share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer ID',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '337',
			'setting_category_id' => '51',
			'setting_category_parent_id' => '15',
			'name' => 'google.consumer_secret',
			'value' => '5dUnvSsVNnLmodPW41Fjn3F5',
			'description' => 'This is the Secrete key used in Gmail share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Client Secret',
			'order' => '17',
			'plugin_name' => ''
		),
		array(
			'id' => '338',
			'setting_category_id' => '61',
			'setting_category_parent_id' => '15',
			'name' => 'linkedin.consumer_key',
			'value' => '9wb2yhmlvt9n',
			'description' => 'This is the Consumer Key used in LinkedIn share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Key',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '339',
			'setting_category_id' => '61',
			'setting_category_parent_id' => '15',
			'name' => 'linkedin.consumer_secret',
			'value' => 'T3jL7EI0qJ5bfoD6',
			'description' => 'This is the Secret Key used in LinkedIn share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Secret',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '342',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'site.launch_mode',
			'value' => 'Launched',
			'description' => 'If Pre-launch mode is selected, users/visitors will only be able to subscribe to your site. Only Administrator (that will be you) can access the site (e.g., http://yourdomain.com/admin). (Turn this on, when you want site traffic before launching the site.). If Private Beta mode is selected, only Administrator and users/visitors those who are having the invite code can sign up to your site and access the site, other can only able to request for invite code.',
			'type' => 'select',
			'options' => 'Pre-launch, Private Beta, Launched',
			'label' => 'Launch Mode',
			'order' => '1',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '343',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'site.private_beta_content',
			'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin blandit nisi non nisl fermentum sit amet volutpat eros tincidunt. Sed tempor blandit gravida.',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Site content for private beta mode',
			'order' => '2',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '344',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'site.pre_launch_content',
			'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin blandit nisi non nisl fermentum sit amet volutpat eros tincidunt. Sed tempor blandit gravida.',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Site content for pre-launch mode',
			'order' => '3',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '345',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'pre_launch.bg_image',
			'value' => '',
			'description' => '(Preferred 950x552)',
			'type' => 'file',
			'options' => '',
			'label' => 'Upload Background Image',
			'order' => '4',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '346',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'pre_launch.bg_image_stretch_type ',
			'value' => 'Stretch',
			'description' => 'The selected option is used for handling background image.
Repeat - Tiles the image. Stretch - Stretches the image to 100% using CSS. AutoResize - Keeps the image resized to 100% of window region using JavaScript.',
			'type' => 'select',
			'options' => 'Repeat, Stretch, AutoResize',
			'label' => 'Stretch Type ',
			'order' => '5',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '347',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'site.no_of_users_to_invite',
			'value' => '50',
			'description' => 'If Private Beta mode is selected, users can invite friends within invite limit. Leave blank for unlimited.',
			'type' => 'text',
			'options' => '',
			'label' => 'Friends invite limit',
			'order' => '6',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '348',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'site.duration_to_invite',
			'value' => 'Daily',
			'description' => 'Invitation will send within duration.',
			'type' => 'select',
			'options' => 'Daily,Weekly,Monthly',
			'label' => 'Invite Duration',
			'order' => '7',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '349',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '2',
			'name' => 'site.no_of_users_to_invite_per_time',
			'value' => '50',
			'description' => 'If Private Beta mode is selected, subscribed users will be invited via cron in selected duration with above given limit. Leave blank for unlimited.',
			'type' => 'text',
			'options' => '',
			'label' => 'Cron invite limit',
			'order' => '8',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '350',
			'setting_category_id' => '65',
			'setting_category_parent_id' => '15',
			'name' => 'google_analytics.access_token',
			'value' => '',
			'description' => 'This will be automatically updated when \"Update Google Analytics Credentials\" link is clicked. (Required for get data from Google Analytics)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Token',
			'order' => '5',
			'plugin_name' => 'IntegratedGoogleAnalytics'
		),
		array(
			'id' => '351',
			'setting_category_id' => '65',
			'setting_category_parent_id' => '15',
			'name' => 'google_analytics.profile_id',
			'value' => '63232568',
			'description' => 'This is the Profile ID to fetch data from Google Analytics. Please refer this <a href=\"##ANALYTICS_IMAGE##\" target=\"_blank\">image</a>. Example: p\'XXXX\'.',
			'type' => 'text',
			'options' => '',
			'label' => 'Profile ID',
			'order' => '4',
			'plugin_name' => 'IntegratedGoogleAnalytics'
		),
		array(
			'id' => '404',
			'setting_category_id' => '67',
			'setting_category_parent_id' => '66',
			'name' => 'cloudflare.is_cloudflare_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable CloudFlare',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '405',
			'setting_category_id' => '67',
			'setting_category_parent_id' => '66',
			'name' => 'cloudflare.token',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'CloudFlare Token',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '406',
			'setting_category_id' => '67',
			'setting_category_parent_id' => '66',
			'name' => 'cloudflare.email',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'CloudFlare Email Id',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '407',
			'setting_category_id' => '68',
			'setting_category_parent_id' => '66',
			'name' => 'is_page_speed_enabled',
			'value' => '1',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '408',
			'setting_category_id' => '69',
			'setting_category_parent_id' => '66',
			'name' => 'cdn.is_cdn_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Pull CDN',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '409',
			'setting_category_id' => '69',
			'setting_category_parent_id' => '66',
			'name' => 'cdn.images',
			'value' => '',
			'description' => 'This is base URL (without trailing slash) for CDN images. (e.g., http://images.yourdomain.com)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN Image URL',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '410',
			'setting_category_id' => '69',
			'setting_category_parent_id' => '66',
			'name' => 'cdn.css',
			'value' => '',
			'description' => 'This is base URL (without trailing slash) for CDN CSS. (e.g., http://css.yourdomain.com)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN CSS URL',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '411',
			'setting_category_id' => '69',
			'setting_category_parent_id' => '66',
			'name' => 'cdn.js',
			'value' => '',
			'description' => 'This is base URL (without trailing slash) for CDN JavaScript. (e.g., http://js.yourdomain.com)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN JS URL',
			'order' => '4',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '412',
			'setting_category_id' => '70',
			'setting_category_parent_id' => '66',
			'name' => 'mail.is_smtp_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable SMTP server',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '413',
			'setting_category_id' => '70',
			'setting_category_parent_id' => '66',
			'name' => 'mail.smtp_host',
			'value' => '',
			'description' => 'Add like ssl://smtp.gmail.com <http://smtp.gmail.com> host name',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP host',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '414',
			'setting_category_id' => '70',
			'setting_category_parent_id' => '66',
			'name' => 'mail.smtp_port',
			'value' => '465',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP port',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '415',
			'setting_category_id' => '70',
			'setting_category_parent_id' => '66',
			'name' => 'mail.smtp_username',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP username',
			'order' => '4',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '416',
			'setting_category_id' => '70',
			'setting_category_parent_id' => '66',
			'name' => 'mail.smtp_password',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP password',
			'order' => '5',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '417',
			'setting_category_id' => '71',
			'setting_category_parent_id' => '66',
			'name' => 'RedisSession.is_redis_session_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Redis',
			'order' => '7',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '418',
			'setting_category_id' => '71',
			'setting_category_parent_id' => '66',
			'name' => 'RedisSession.hostname',
			'value' => '192.168.1.7',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Redis Host Name',
			'order' => '8',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '419',
			'setting_category_id' => '71',
			'setting_category_parent_id' => '66',
			'name' => 'RedisSession.port',
			'value' => '1377',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Redis Port',
			'order' => '9',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '420',
			'setting_category_id' => '72',
			'setting_category_parent_id' => '66',
			'name' => 'Memcached.is_memcached_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Memcached',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '421',
			'setting_category_id' => '72',
			'setting_category_parent_id' => '66',
			'name' => 'Memcached.servers',
			'value' => '192.168.1.7',
			'description' => 'Add multiple server host name (seperated by comma)',
			'type' => 'text',
			'options' => '',
			'label' => 'Memcached Servers',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '422',
			'setting_category_id' => '73',
			'setting_category_parent_id' => '66',
			'name' => 'HtmlCache.is_htmlcache_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Full-page Caching',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '423',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.is_enabled',
			'value' => '0',
			'description' => 'Uncheck this to revert back to using your own web host for storage and delivery at anytime',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable storing of files to Amazon S3 and serving files from Amazon S3',
			'order' => '10',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '424',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.end_point',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'End Point',
			'order' => '11',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '425',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.aws_access_key',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Key',
			'order' => '12',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '426',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.aws_secret_key',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Secret Key',
			'order' => '13',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '427',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.bucket_name',
			'value' => '',
			'description' => '##TEST_CONNECTION##',
			'type' => 'text',
			'options' => '',
			'label' => 'Bucket Name',
			'order' => '14',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '428',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.keep_copy_in_local',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Keep copy in local',
			'order' => '15',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '429',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.is_cname_enabled',
			'value' => '0',
			'description' => 'For more details please refer <a title=\"For more info\" target=\"_blank\" href=\"http://docs.amazonwebservices.com/AmazonS3/2006-03-01/VirtualHosting.html\">http://docs.amazonwebservices.com/AmazonS3/2006-03-01/VirtualHosting.html</a>',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Bucket is setup for virtual hosting',
			'order' => '16',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '430',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '66',
			'name' => 's3.upload_static_content_enabled',
			'value' => '0',
			'description' => 'Static content such as CSS, JavaScript, images files in <code>webroot</code> folder. Uncheck this to revert back to using own server for delivery at anytime.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable to deliver all the static contents from Amazon S3',
			'order' => '17',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '352',
			'setting_category_id' => '76',
			'setting_category_parent_id' => '75',
			'name' => 'invite.facebook',
			'value' => 'Check out this website ##SITE_NAME## ##REFERRAL_URL##',
			'description' => '##SITE_NAME## ##REFERRAL_URL##',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Invite Facebook Content',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '353',
			'setting_category_id' => '76',
			'setting_category_parent_id' => '75',
			'name' => 'invite.twitter',
			'value' => 'Check out this website ##REFERRAL_URL##',
			'description' => '##REFERRAL_URL##',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Invite Twitter Content',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '354',
			'setting_category_id' => '77',
			'setting_category_parent_id' => '75',
			'name' => 'share.facebook',
			'value' => 'Check out this website ##SITE_NAME## ##SHARE_URL##',
			'description' => '##SITE_NAME## ##SHARE_URL##',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Facebook Share content ',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '355',
			'setting_category_id' => '77',
			'setting_category_parent_id' => '75',
			'name' => 'share.twitter',
			'value' => 'Check out this property ##PROPERTY_NAME## ##SHARE_URL##',
			'description' => '##PROPERTY_NAME## ##SHARE_URL##',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Twitter Share content',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '356',
			'setting_category_id' => '62',
			'setting_category_parent_id' => '15',
			'name' => 'googleplus.consumer_secret',
			'value' => 'h9al8t_gV7Gm_CFC6fMwjGsT',
			'description' => 'This is the Secrete key used in Google+ share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Secret key',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '357',
			'setting_category_id' => '62',
			'setting_category_parent_id' => '15',
			'name' => 'googleplus.consumer_key',
			'value' => '261544905009-k0q92ngg9812q9fq831ckcuoddgt2eqp.apps.googleusercontent.com',
			'description' => 'This is the Consumer ID used in Google+ share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer ID',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '365',
			'setting_category_id' => '80',
			'setting_category_parent_id' => '1',
			'name' => 'system.captcha_type',
			'value' => 'Solve Media',
			'description' => 'The selected type will be used for CAPTCHA display in sign up and contact us pages.',
			'type' => 'select',
			'options' => 'Normal,Solve Media',
			'label' => 'CAPTCHA Type',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '366',
			'setting_category_id' => '81',
			'setting_category_parent_id' => '15',
			'name' => 'captcha.challenge_key',
			'value' => 'oR.X9IGEcuYNu3pk7m.ZN7BiD-M-vHFp',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Challenge Key',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '367',
			'setting_category_id' => '81',
			'setting_category_parent_id' => '15',
			'name' => 'captcha.verification_key',
			'value' => '00MsxSO3v0GQRB8TFPla0rY9dzeovpSd',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Verification Key',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '368',
			'setting_category_id' => '81',
			'setting_category_parent_id' => '15',
			'name' => 'captcha.hash_key',
			'value' => 'G9VT4C021Q1ExAKN8Wltf.cxMX-V9wfG',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Authentication Hash Key',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '372',
			'setting_category_id' => '86',
			'setting_category_parent_id' => '82',
			'name' => 'widget.user_script',
			'value' => '<img src=\"http://placehold.it/728X90\" alt =\"728X90\" width=\"728\" height=\"90\"/>',
			'description' => 'This is the user page script, used for display banners on user page',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '373',
			'setting_category_id' => '38',
			'setting_category_parent_id' => '8',
			'name' => 'wallet.wallet_fee_payer',
			'value' => 'Site',
			'description' => '',
			'type' => 'radio',
			'options' => 'User,Site',
			'label' => 'Who will pay the gateway fee for wallet',
			'order' => '0',
			'plugin_name' => 'Sudopay'
		),
		array(
			'id' => '374',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '5',
			'name' => 'user.days_after_fetch_facebook_friends',
			'value' => '1',
			'description' => 'Every above given duration friends will fetch from Facebook.',
			'type' => 'text',
			'options' => '',
			'label' => 'Facebook friends fetch duration',
			'order' => '0',
			'plugin_name' => ''
		),
	);

}
