<?php
/**
 * Burrow
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    Burrow
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class UserData {

	public $table = 'users';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2009-04-28 10:09:35',
			'modified' => '2012-07-10 02:20:37',
			'role_id' => '1',
			'attachment_id' => '0',
			'username' => 'admin',
			'email' => 'productdemo.admin@gmail.com',
			'password' => '$1$Iz]ZII12$tTb.EuP3eScxM50yqQ52S.',
			'available_wallet_amount' => '0.00',
			'blocked_amount' => '0.00',
			'cleared_amount' => '0.00',
			'dns' => '',
			'total_amount_withdrawn' => '0.00',
			'total_withdraw_request_count' => '0',
			'total_amount_deposited' => '0.00',
			'property_feedback_count' => '0',
			'host_expired_count' => '0',
			'host_canceled_count' => '0',
			'host_rejected_count' => '0',
			'host_completed_count' => '0',
			'host_review_count' => '0',
			'host_arrived_count' => '0',
			'host_confirmed_count' => '0',
			'host_waiting_for_acceptance_count' => '0',
			'host_negotiation_count' => '0',
			'host_payment_cleared_count' => '0',
			'host_total_booked_count' => '0',
			'host_total_lost_booked_count' => '0',
			'host_total_earned_amount' => '0.00',
			'host_total_lost_amount' => '0.00',
			'host_total_pipeline_amount' => '0.00',
			'host_total_site_revenue' => '0.00',
			'travel_expired_count' => '0',
			'travel_rejected_count' => '0',
			'travel_canceled_count' => '0',
			'travel_review_count' => '0',
			'travel_completed_count' => '0',
			'travel_arrived_count' => '0',
			'travel_confirmed_count' => '0',
			'travel_payment_pending_count' => '0',
			'travel_waiting_for_acceptance_count' => '0',
			'travel_negotiation_count' => '0',
			'travel_payment_cleared_count' => '0',
			'traveler_positive_feedback_count' => '0',
			'traveler_property_user_count' => '0',
			'travel_total_booked_count' => '0',
			'travel_total_booked_amount' => '0.00',
			'travel_total_lost_booked_count' => '0',
			'travel_total_site_revenue' => '0.00',
			'positive_feedback_count' => '0',
			'property_favorite_count' => '0',
			'property_user_count' => '0',
			'request_count' => '0',
			'property_count' => '0',
			'property_pending_approval_count' => '0',
			'property_inactive_count' => '0',
			'referred_by_user_id' => '0',
			'referred_by_user_count' => '0',
			'referred_booking_count' => '0',
			'affiliate_refer_booking_count' => '0',
			'user_referred_count' => '0',
			'total_commission_pending_amount' => '0.00',
			'total_commission_canceled_amount' => '0.00',
			'total_commission_completed_amount' => '0.00',
			'commission_line_amount' => '0.00',
			'commission_withdraw_request_amount' => '0.00',
			'commission_paid_amount' => '0.00',
			'cim_profile_id' => '6398820',
			'user_login_count' => '0',
			'user_view_count' => '0',
			'user_friend_count' => '0',
			'user_comment_count' => '0',
			'cookie_hash' => '',
			'cookie_time_modified' => '0000-00-00 00:00:00',
			'is_agree_terms_conditions' => '1',
			'is_active' => '1',
			'is_email_confirmed' => '1',
			'is_affiliate_user' => '0',
			'ip_id' => '0',
			'last_login_ip_id' => '0',
			'last_logged_in_time' => '0000-00-00 00:00:00',
			'user_facebook_friend_count' => '0',
			'is_show_facebook_friends' => '0',
			'is_facebook_friends_fetched' => '0',
			'network_fb_user_id' => '0',
			'last_facebook_friend_fetched_date' => '0000-00-00',
			'is_paid' => '0',
			'pay_key' => '',
			'security_question_id' => '0',
			'security_answer' => '',
			'is_facebook_register' => '0',
			'is_twitter_register' => '0',
			'is_google_register' => '0',
			'is_googleplus_register' => '0',
			'is_yahoo_register' => '0',
			'is_linkedin_register' => '0',
			'is_openid_register' => '0',
			'facebook_user_id' => '',
			'facebook_access_token' => '',
			'twitter_user_id' => '',
			'twitter_access_token' => '',
			'twitter_access_key' => '',
			'google_user_id' => '',
			'google_access_token' => '',
			'googleplus_user_id' => '',
			'yahoo_user_id' => '',
			'yahoo_access_token' => '',
			'linkedin_user_id' => '',
			'linkedin_access_token' => '',
			'openid_user_id' => '',
			'twitter_avatar_url' => '',
			'google_avatar_url' => '',
			'googleplus_avatar_url' => '',
			'linkedin_avatar_url' => '',
			'facebook_friends_count' => '0',
			'twitter_followers_count' => '0',
			'google_contacts_count' => '0',
			'googleplus_contacts_count' => '0',
			'yahoo_contacts_count' => '0',
			'linkedin_contacts_count' => '0',
			'user_openid_count' => '0',
			'is_skipped_fb' => '0',
			'is_skipped_twitter' => '0',
			'is_skipped_google' => '0',
			'is_skipped_yahoo' => '0',
			'is_skipped_linkedin' => '0',
			'is_facebook_connected' => '0',
			'is_twitter_connected' => '0',
			'is_google_connected' => '0',
			'is_googleplus_connected' => '0',
			'is_yahoo_connected' => '0',
			'is_linkedin_connected' => '0',
			'site_state_id' => '0',
			'user_avatar_source_id' => '0',
			'mobile_app_hash' => '',
			'mobile_app_time_modified' => '0000-00-00 00:00:00',
			'is_idle' => '1',
			'is_property_posted' => '0',
			'is_requested' => '0',
			'is_property_booked' => '0',
			'invite_count' => '0',
			'activity_message_id' => '0',
			'payment_gateway_id' => '0',
			'sudopay_pay_key' => '',
			'sudopay_gateway_id' => '0',
			'sudopay_payment_id' => '0',
			'sudopay_revised_amount' => '0.00',
			'sudopay_token' => '',
			'pwd_reset_token' => '',
			'pwd_reset_requested_date' => '0000-00-00 00:00:00'
		),
	);

}
